"""Python wrapper for Blender's headless GLB auto-rigging script."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional, Union


PathLike = Union[str, os.PathLike[str]]
BLENDER_SCRIPT = Path(__file__).resolve().parent / "scripts" / "auto_rig_glb.py"
DEFAULT_TIMEOUT_SECONDS = 15 * 60


class AutoRigError(RuntimeError):
    """Raised when Blender cannot produce a rigged GLB."""


def _resolve_blender(executable: Optional[str] = None) -> str:
    """Find Blender, preferring an explicit argument and then environment/PATH."""
    configured = executable or os.environ.get("BLENDER_BIN") or os.environ.get("BLENDER")
    if configured:
        candidate = os.path.expandvars(os.path.expanduser(configured))
        candidate_path = Path(candidate)
        if candidate_path.is_file():
            return str(candidate_path.resolve())
        located = shutil.which(candidate)
        if located:
            return located
        raise AutoRigError(
            f"No se encontró Blender en {candidate!r}. Define BLENDER_BIN con la ruta "
            "al ejecutable de Blender o añade blender a PATH."
        )

    located = shutil.which("blender")
    if located:
        return located
    raise AutoRigError(
        "El auto-rigging requiere Blender 3.6 o posterior. No se encontró `blender` "
        "en PATH; instala Blender o define BLENDER_BIN con la ruta al ejecutable."
    )


def _output_tail(stdout: object, stderr: object, limit: int = 30) -> str:
    """Return a short, readable tail of Blender's output for error messages."""
    parts = []
    for value in (stdout, stderr):
        if isinstance(value, bytes):
            value = value.decode("utf-8", errors="replace")
        if value:
            parts.extend(str(value).splitlines())
    return "\n".join(parts[-limit:])


def auto_rig_glb(
    input_path: PathLike,
    output_path: PathLike,
    *,
    blender_executable: Optional[str] = None,
    timeout: Optional[float] = DEFAULT_TIMEOUT_SECONDS,
) -> Path:
    """Import a TRELLIS GLB in headless Blender, rig it, and export a skinned GLB.

    Args:
        input_path: Textured GLB generated by TRELLIS.
        output_path: Destination for the GLB containing the generated armature.
        blender_executable: Optional Blender executable override. By default the
            ``BLENDER_BIN``/``BLENDER`` environment variables and then ``PATH``
            are checked.
        timeout: Maximum Blender runtime in seconds, or ``None`` for no timeout.

    Returns:
        The resolved destination path.

    Raises:
        AutoRigError: If the source, Blender executable, Blender script, or
            exported GLB is unavailable, or Blender reports a failure.
    """
    source = Path(input_path).expanduser().resolve()
    destination = Path(output_path).expanduser().resolve()

    if not source.is_file():
        raise AutoRigError(f"No existe el GLB de entrada: {source}")
    if source.suffix.lower() != ".glb":
        raise AutoRigError(f"Se esperaba un archivo .glb de entrada: {source}")
    if destination.suffix.lower() != ".glb":
        raise AutoRigError(f"El archivo de salida debe tener extensión .glb: {destination}")
    if source == destination:
        raise AutoRigError("El GLB riggeado debe guardarse en una ruta distinta al original.")
    if not BLENDER_SCRIPT.is_file():
        raise AutoRigError(f"No se encontró el script de Blender: {BLENDER_SCRIPT}")
    if timeout is not None and timeout <= 0:
        raise ValueError("timeout debe ser un número positivo o None")

    blender = _resolve_blender(blender_executable)
    destination.parent.mkdir(parents=True, exist_ok=True)
    # Avoid accidentally returning a previous run's output if Blender fails.
    destination.unlink(missing_ok=True)

    command = [
        blender,
        "--background",
        "--factory-startup",
        "--python",
        str(BLENDER_SCRIPT),
        "--",
        "--input",
        str(source),
        "--output",
        str(destination),
    ]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        destination.unlink(missing_ok=True)
        tail = _output_tail(exc.stdout, exc.stderr)
        details = f"\nSalida de Blender:\n{tail}" if tail else ""
        raise AutoRigError(
            f"Blender superó el límite de tiempo de {timeout} segundos.{details}"
        ) from exc
    except OSError as exc:
        destination.unlink(missing_ok=True)
        raise AutoRigError(f"No se pudo iniciar Blender ({blender}): {exc}") from exc

    if result.returncode != 0:
        destination.unlink(missing_ok=True)
        tail = _output_tail(result.stdout, result.stderr)
        details = f"\nSalida de Blender:\n{tail}" if tail else ""
        raise AutoRigError(
            f"Blender terminó con código {result.returncode} al riggear el modelo.{details}"
        )
    if not destination.is_file() or destination.stat().st_size == 0:
        destination.unlink(missing_ok=True)
        tail = _output_tail(result.stdout, result.stderr)
        details = f"\nSalida de Blender:\n{tail}" if tail else ""
        raise AutoRigError(
            f"Blender terminó sin crear un GLB riggeado válido.{details}"
        )

    return destination
